-- =========================================================
-- PHASE 2: CUSTOMER REQUEST FLOW
-- =========================================================

DO $$ BEGIN
    CREATE TYPE public.job_status AS ENUM ('REQUESTED', 'APPROVED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE public.job_item_status AS ENUM ('PENDING', 'COLLECTED', 'DELIVERED');
EXCEPTION WHEN duplicate_object THEN null; END $$;

CREATE SEQUENCE IF NOT EXISTS public.job_code_seq START WITH 1001;

CREATE TABLE IF NOT EXISTS public.jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_code TEXT NOT NULL UNIQUE DEFAULT ('MC-' || LPAD(nextval('public.job_code_seq')::text, 6, '0')),
  customer_id UUID NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  pickup_address TEXT NOT NULL CHECK (length(trim(pickup_address)) > 0),
  destination_address TEXT NOT NULL CHECK (length(trim(destination_address)) > 0),
  move_date DATE NOT NULL,
  start_time TIME NOT NULL,
  instructions TEXT,
  status public.job_status NOT NULL DEFAULT 'REQUESTED',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.job_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id UUID NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
  name TEXT NOT NULL CHECK (length(trim(name)) > 0),
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  status public.job_item_status NOT NULL DEFAULT 'PENDING'
);

ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_items ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Customers can view own jobs" ON public.jobs FOR SELECT TO authenticated USING (auth.uid() = customer_id);
CREATE POLICY "Customers can create own jobs" ON public.jobs FOR INSERT TO authenticated WITH CHECK (auth.uid() = customer_id AND status = 'REQUESTED');
CREATE POLICY "Customers can view items" ON public.job_items FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.jobs WHERE id = job_items.job_id AND customer_id = auth.uid()));

-- Atomic Request RPC
CREATE OR REPLACE FUNCTION public.create_move_request(
  p_pickup_address TEXT, p_destination_address TEXT, p_move_date DATE, p_start_time TIME, p_instructions TEXT, p_items JSONB
) RETURNS TABLE (job_id UUID, job_code TEXT) AS $$
DECLARE v_job_id UUID; v_job_code TEXT;
BEGIN
  INSERT INTO public.jobs (customer_id, pickup_address, destination_address, move_date, start_time, instructions, status)
  VALUES (auth.uid(), trim(p_pickup_address), trim(p_destination_address), p_move_date, p_start_time, nullif(trim(p_instructions), ''), 'REQUESTED')
  RETURNING id, jobs.job_code INTO v_job_id, v_job_code;

  INSERT INTO public.job_items (job_id, name, quantity)
  SELECT v_job_id, trim(item.name), item.quantity FROM jsonb_to_recordset(p_items) AS item(name TEXT, quantity INTEGER);

  RETURN QUERY SELECT v_job_id, v_job_code;
END;
$$ LANGUAGE plpgsql SECURITY INVOKER;

GRANT EXECUTE ON FUNCTION public.create_move_request TO authenticated;
