-- ============================================================
-- MOVE CREW - FULL DATABASE SETUP (PHASES 1-10)
-- ============================================================

-- 1. ENUMS & SEQUENCES
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN CREATE TYPE public.user_role AS ENUM ('customer', 'admin', 'mover'); END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'job_status') THEN CREATE TYPE public.job_status AS ENUM ('REQUESTED', 'APPROVED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', 'CANCELLED'); END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'job_item_status') THEN CREATE TYPE public.job_item_status AS ENUM ('PENDING', 'COLLECTED', 'DELIVERED'); END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'assignment_status') THEN CREATE TYPE public.assignment_status AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED'); END IF;
END $$;

CREATE SEQUENCE IF NOT EXISTS public.job_code_seq START WITH 1001;

-- 2. CORE TABLES
CREATE TABLE IF NOT EXISTS public.users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  phone TEXT,
  role public.user_role NOT NULL DEFAULT 'customer',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.customers (id UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS public.movers (id UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE, employee_code TEXT UNIQUE NOT NULL);

CREATE TABLE IF NOT EXISTS public.jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_code TEXT NOT NULL UNIQUE DEFAULT ('MC-' || LPAD(nextval('public.job_code_seq')::text, 6, '0')),
  customer_id UUID NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  pickup_address TEXT NOT NULL,
  destination_address TEXT NOT NULL,
  move_date DATE NOT NULL,
  start_time TIME NOT NULL,
  instructions TEXT,
  status public.job_status NOT NULL DEFAULT 'REQUESTED',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.job_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id UUID NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  status public.job_item_status NOT NULL DEFAULT 'PENDING'
);

CREATE TABLE IF NOT EXISTS public.assignments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id UUID NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
  mover_id UUID NOT NULL REFERENCES public.movers(id) ON DELETE CASCADE,
  status public.assignment_status NOT NULL DEFAULT 'PENDING',
  responded_at TIMESTAMPTZ,
  CONSTRAINT assignments_job_mover_unique UNIQUE (job_id, mover_id)
);

CREATE TABLE IF NOT EXISTS public.mover_locations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  assignment_id UUID NOT NULL REFERENCES public.assignments(id) ON DELETE CASCADE,
  mover_id UUID NOT NULL REFERENCES public.movers(id) ON DELETE CASCADE,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  accuracy DOUBLE PRECISION,
  recorded_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.time_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  assignment_id UUID NOT NULL REFERENCES public.assignments(id) ON DELETE CASCADE,
  mover_id UUID NOT NULL REFERENCES public.movers(id) ON DELETE CASCADE,
  clock_in_at TIMESTAMPTZ,
  clock_out_at TIMESTAMPTZ,
  status TEXT DEFAULT 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS public.reviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id UUID NOT NULL REFERENCES public.jobs(id) UNIQUE,
    customer_id UUID NOT NULL REFERENCES public.users(id),
    mover_id UUID NOT NULL REFERENCES public.users(id),
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. SECURITY (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mover_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.time_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- 4. HELPER FUNCTIONS
CREATE OR REPLACE FUNCTION public.is_admin() RETURNS BOOLEAN AS $$ SELECT EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin'); $$ LANGUAGE sql STABLE SECURITY DEFINER;
CREATE OR REPLACE FUNCTION public.is_mover_assigned(p_job_id UUID) RETURNS BOOLEAN AS $$ SELECT EXISTS (SELECT 1 FROM public.assignments WHERE job_id = p_job_id AND mover_id = auth.uid()); $$ LANGUAGE sql STABLE SECURITY DEFINER;

-- 5. POLICIES (Simplified)
CREATE POLICY "Users view own profile" ON public.users FOR SELECT USING (auth.uid() = id OR public.is_admin());
CREATE POLICY "Customer jobs" ON public.jobs FOR ALL USING (customer_id = auth.uid() OR public.is_admin() OR public.is_mover_assigned(id));
CREATE POLICY "Assignment view" ON public.assignments FOR SELECT USING (mover_id = auth.uid() OR public.is_admin());
CREATE POLICY "Location stream" ON public.mover_locations FOR SELECT USING (auth.uid() = mover_id OR public.is_admin() OR EXISTS (SELECT 1 FROM public.assignments a JOIN public.jobs j ON a.job_id = j.id WHERE a.id = mover_locations.assignment_id AND j.customer_id = auth.uid()));
CREATE POLICY "Review access" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "Review insert" ON public.reviews FOR INSERT WITH CHECK (auth.uid() = customer_id);

-- 6. RPCs
CREATE OR REPLACE FUNCTION public.create_move_request(p_pickup_address TEXT, p_destination_address TEXT, p_move_date DATE, p_start_time TIME, p_instructions TEXT, p_items JSONB) RETURNS TABLE (job_id UUID, job_code TEXT) AS $$
DECLARE v_job_id UUID; v_job_code TEXT;
BEGIN
  INSERT INTO public.jobs (customer_id, pickup_address, destination_address, move_date, start_time, instructions, status)
  VALUES (auth.uid(), trim(p_pickup_address), trim(p_destination_address), p_move_date, p_start_time, p_instructions, 'REQUESTED') RETURNING id, jobs.job_code INTO v_job_id, v_job_code;
  INSERT INTO public.job_items (job_id, name, quantity) SELECT v_job_id, trim(item.name), item.quantity FROM jsonb_to_recordset(p_items) AS item(name TEXT, quantity INTEGER);
  RETURN QUERY SELECT v_job_id, v_job_code;
END; $$ LANGUAGE plpgsql SECURITY INVOKER;

CREATE OR REPLACE FUNCTION public.complete_job(p_job_id UUID) RETURNS VOID AS $$ BEGIN UPDATE public.jobs SET status = 'COMPLETED', completed_at = NOW() WHERE id = p_job_id; END; $$ LANGUAGE plpgsql SECURITY DEFINER;

-- 7. REALTIME
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'mover_locations') THEN ALTER PUBLICATION supabase_realtime ADD TABLE mover_locations; END IF; END $$;

-- 8. VIEWS
CREATE OR REPLACE VIEW public.mover_ratings AS SELECT mover_id, AVG(rating)::NUMERIC(3,2) as avg_rating, COUNT(*) as total_reviews FROM public.reviews GROUP BY mover_id;
CREATE OR REPLACE VIEW public.admin_job_summary AS SELECT status, COUNT(*) as total_count FROM public.jobs GROUP BY status;
